// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © henry_oliver

//@version=6
indicator(title = "Stochastic", shorttitle = "🎲 Stoch", format = format.price, precision = 2, timeframe = "", timeframe_gaps = true)

// 🧱 CONSTANTS
const string GROUP_GENERAL = "⚙️ General"
const string GROUP_STOCH = "📈 Stochastic"
const string GROUP_STYLE = "🎨 Style"
const string GROUP_BANDS = "📏 Bands"

// Nord Theme Color
// Polar Night
const color NORD0 = #2E3440
const color NORD1 = #3B4252
const color NORD2 = #434C5E
const color NORD3 = #4C566A
// Snow Storm  
const color NORD4 = #D8DEE9
const color NORD5 = #E5E9F0
const color NORD6 = #ECEFF4
// Frost
const color NORD7 = #8FBCBB
const color NORD8 = #88C0D0
const color NORD9 = #81A1C1
const color NORD10 = #5E81AC
// Aurora
const color NORD11 = #BF616A
const color NORD12 = #D08770
const color NORD13 = #EBCB8B
const color NORD14 = #A3BE8C
const color NORD15 = #B48EAD

// 🎛️ USER INPUT SETTINGS

// Stochastic Input Settings
int periodK = input.int(defval = 5, title = "%K Length", minval = 1, group = GROUP_STOCH)
int smoothK = input.int(defval = 2, title = "%K Smoothing", minval = 1, group = GROUP_STOCH)
int periodD = input.int(defval = 3, title = "%D Smoothing", minval = 1, group = GROUP_STOCH)

// Stochastic Colors & Width
color colorK = input.color(defval = NORD3, title = "%K Color", group = GROUP_STYLE)
int widthK = input.int(defval = 2, title = "%K Width", minval = 1, maxval = 10, group = GROUP_STYLE)
color colorD = input.color(defval = color.new(color = NORD2, transp = 60), title = "%D Color", group = GROUP_STYLE)
int widthD = input.int(defval = 4, title = "%D Width", minval = 1, maxval = 10, group = GROUP_STYLE)

// Band Settings
bool showUpperBand = input.bool(defval = true, title = "Show Upper Band", group = GROUP_BANDS)
float upperBand = input.float(defval = 80, title = "Upper Band", minval = 50, maxval = 100, group = GROUP_BANDS)
bool showUpperMidBand = input.bool(defval = true, title = "Show Upper Mid Band", group = GROUP_BANDS)
float upperMidBand = input.float(defval = 55, title = "Upper Mid Band", minval = 50, maxval = 100, group = GROUP_BANDS)
bool showMiddleBand = input.bool(defval = false, title = "Show Middle Band", group = GROUP_BANDS)
float middleBand = input.float(defval = 50, title = "Middle Band", minval = 0, maxval = 100, group = GROUP_BANDS)
bool showLowerMidBand = input.bool(defval = true, title = "Show Lower Mid Band", group = GROUP_BANDS)
float lowerMidBand = input.float(defval = 45, title = "Lower Mid Band", minval = 0, maxval = 50, group = GROUP_BANDS)
bool showLowerBand = input.bool(defval = true, title = "Show Lower Band", group = GROUP_BANDS)
float lowerBand = input.float(defval = 20, title = "Lower Band", minval = 0, maxval = 50, group = GROUP_BANDS)
color bandColor = input.color(defval = NORD3, title = "Band Color", group = GROUP_BANDS)
int bandWidth = input.int(defval = 1, title = "Band Width", minval = 1, maxval = 10, group = GROUP_BANDS)


// 🧮 CALCULATIONS
// Calculate Stochastic
float k = ta.sma(source = ta.stoch(source = close, high = high, low = low, length = periodK), length = smoothK)
float d = ta.sma(source = k, length = periodD)

// 📊 PLOT
// Plot Stochastic Lines
plot(series = d, title = "%D", color = colorD, linewidth = widthD)
plot(series = k, title = "%K", color = colorK, linewidth = widthK)

// Plot Bands
h0 = hline(price = showUpperBand ? upperBand : na, title = "Upper Band", color = bandColor, linewidth = bandWidth, linestyle = hline.style_dashed)
hline(price = showUpperMidBand ? upperMidBand : na, title = "Upper Mid Band", color = bandColor, linewidth = bandWidth, linestyle = hline.style_dashed)
hline(price = showMiddleBand ? middleBand : na, title = "Middle Band", color = color.new(color = bandColor, transp = 50), linewidth = bandWidth)
hline(price = showLowerMidBand ? lowerMidBand : na, title = "Lower Mid Band", color = bandColor, linewidth = bandWidth, linestyle = hline.style_dashed)
h1 = hline(price = showLowerBand ? lowerBand : na, title = "Lower Band", color = bandColor, linewidth = bandWidth, linestyle = hline.style_dashed)
